Repository googleapis/cloud-trace-nodejs, pull requests merged in 2020-07, with the labels that each got.

#1289 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#1290 build: update gitattributes
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#1294 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#1293 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#1299 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes
