Repository googleapis/cloud-trace-nodejs, pull requests merged in 2020-09, with the labels that each got.

#1306 build: update to latest build and docs config
  .gitattributes
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  README.md
  api-extractor.json
  synth.metadata
Labels: cla: yes, context: partial

#1308 build(test): recursively find test files; fail on unsupported dependency versions
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#1310 chore: update language for inclusivity
  test/test-cls.ts
  test/test-plugin-loader.ts
Labels: api: cloudtrace, cla: yes
