Repository googleapis/cloud-trace-nodejs, pull requests merged in 2021-02, with the labels that each got.

#1329 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: api: cloudtrace, cla: yes

#1315 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: api: cloudtrace, cla: yes, context: full

#1309 refactor: avoid semver where possible
  src/cls.ts
  src/index.ts
  src/plugins/plugin-http.ts
Labels: api: cloudtrace, cla: yes

#1328 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: api: cloudtrace, automerge, cla: yes

#1333 chore: update CoC, samples index, build config
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: api: cloudtrace, cla: yes, context: partial
