Repository googleapis/cloud-trace-nodejs, pull requests merged in 2022-08, with the labels that each got.

#1460 chore: update post-processor
  .github/.OwlBot.lock.yaml
Labels: api: cloudtrace, size: xs

#1412 feat(mysql): propagate "fields" in MySQL
  src/plugins/plugin-mysql.ts
Labels: api: cloudtrace, size: xs

#1406 chore(docs): Replace "Stackdriver Trace" with "Cloud Trace" in the README file
  .readme-partials.yaml
  README.md
Labels: cla: yes, api: cloudtrace, size: s

#1465 chore: Use API hostname subdomain for api_shortname
  .repo-metadata.json
Labels: automerge, api: cloudtrace, size: xs

#1461 chore(deps): update dependency @types/node to v16
  package.json
  src/tracing.ts
  test/test-cls.ts
  test/test-trace-cluster.ts
Labels: automerge, api: cloudtrace, size: s

#1471 chore: pin some dependency versions
  .github/workflows/ci.yaml
  package.json
Labels: api: cloudtrace, size: xs

#1467 fix: Remove unused type arg
  src/cls.ts
Labels: api: cloudtrace, size: xs

#1470 Return the patched promise, not the original one
  src/plugins/plugin-pg.ts
Labels: api: cloudtrace, size: xs
